version: '3.1'

services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 30001:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 30002:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo
    ports:
      - 30003:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  app:
    mem_limit: 512mb
    build:
      context: D:\epam\projects\mongo-homework\docker\dockerfiles
      
    container_name: app
    image: app:latest
    ports:
      - "8080:8080"
    restart:
      on-failure:10